spring:
    main:
      banner-mode: "off"
    jpa:
      database: mysql
      show-sql: false
      hibernate:
        ddl-auto: none
      database-platform: org.hibernate.dialect.MySQLDialect
    datasource:
      url: jdbc:mysql://localhost/spring_test?zeroDateTimeBehavior=convertToNull
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver
